# Generated by Django 3.2.9 on 2022-01-09 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_auto_20220109_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='website',
            name='landing_page',
        ),
    ]
