# Generated by Django 3.2.9 on 2022-01-09 22:57

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0008_auto_20220109_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='PROFILE PIC', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='website',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='website',
            name='design',
            field=models.ManyToManyField(blank=True, related_name='design', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='website',
            name='landing_page',
            field=cloudinary.models.CloudinaryField(default='PAGE PIC', max_length=255, verbose_name='Landing page image'),
        ),
        migrations.AddField(
            model_name='website',
            name='usability',
            field=models.ManyToManyField(blank=True, related_name='usability', to=settings.AUTH_USER_MODEL),
        ),
    ]
